---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: nginx
  name: nginx
  namespace: app
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: dockerhub.com/nginx-unprivileged/nginx-unprivileged@sha256:eb36ba45cca975fa19bfb64b654f5e400d1468d160e3ad1d53062ff4a26ba4ac
        imagePullPolicy: IfNotPresent
        name: nginx-unprivileged
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-14T06:26:53Z"
  labels:
    app: nginx
  name: nginx-svc
  namespace: app
  resourceVersion: "123898496"
  uid: ae39c1f5-b741-4e15-9db0-06362038d2ac
spec:
  clusterIP: 192.168.66.181
  clusterIPs:
  - 192.168.66.181
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
---
